language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
env:
  - DJANGO=1.4.5
  - DJANGO=1.5.1
install:
  - pip install Django==$DJANGO
  - pip install .
script:
  - make test
notifications:
  email: false
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=1.4.5
