language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
env:
    - DJANGO=1.4.20
    - DJANGO=1.5.12
    - DJANGO=1.6.11
    - DJANGO=1.7.7
install:
    - pip install Django==$DJANGO
    - pip install .
script:
    - make test
notifications:
    email: false
matrix:
    exclude:
        - python: "2.6"
          env: DJANGO=1.7.7
        - python: "3.3"
          env: DJANGO=1.4.20
        - python: "3.4"
          env: DJANGO=1.4.20
